on:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: release ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: amd64
    steps:
    - uses: actions/checkout@v4
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goarch: ${{ matrix.goarch }}
        goos: ${{ matrix.goos }}
        extra_files: "LICENSE"
        ldflags: "-X github.com/dvdmuckle/spc/cmd.version=${{ github.event.release.tag_name }}"
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: spc
          create-pullrequest: true
          homebrew-tap: dvdmuckle/homebrew-tap
          tag-name: "${{ github.event.release.tag_name }}"
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_BUMP }}
