on: 
  release:
    types:
      - published
name: Trigger Fedora Copr Build
jobs:
  build:
    name: Submit a build from Fedora container
    # Run in Fedora container on Ubuntu VM (no direct Fedora support)
    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"
      - name: Check spec for bumped version
        run: |
          grep -q ${{ github.event.release.tag_name }} spc.spec || { echo "Version not bumped!" && exit 1; }

      - name: Install tooling for source RPM build
        run: |
          dnf -y install copr-cli

      - name: Submit the build by uploading the spec
        run: copr build --nowait dvdmuckle/spc spc.spec